"""Estructuras canonicas de draft CapCut (extraidas de un draft real del usuario).

Al ser la plantilla un esqueleto vacio, se usan estos shapes como modelo
y se adaptan en generate(): ids, rutas, timeranges y duraciones se generan.
*NO* tocar estos valores a mano salvo para adaptarse a una version nueva de CapCut.
"""

from __future__ import annotations

PHOTO_MATERIAL = {'id': '',
 'unique_id': '',
 'type': 'photo',
 'duration': 10800000000,
 'path': '',
 'media_path': '',
 'local_id': '',
 'has_audio': False,
 'reverse_path': '',
 'intensifies_path': '',
 'reverse_intensifies_path': '',
 'intensifies_audio_path': '',
 'cartoon_path': '',
 'width': 1920,
 'height': 1080,
 'category_id': '',
 'category_name': 'local',
 'material_id': '',
 'material_name': '001_Spider-Man balanceándose entre edificios, Spider-Man Hom.jpg',
 'material_url': '',
 'crop': {'upper_left_x': 0.0,
          'upper_left_y': 0.0,
          'upper_right_x': 1.0,
          'upper_right_y': 0.0,
          'lower_left_x': 0.0,
          'lower_left_y': 1.0,
          'lower_right_x': 1.0,
          'lower_right_y': 1.0},
 'crop_ratio': 'free',
 'audio_fade': None,
 'crop_scale': 1.0,
 'extra_type_option': 0,
 'stable': {'stable_level': 0, 'matrix_path': '', 'time_range': {'start': 0, 'duration': 0}},
 'matting': {'flag': 0,
             'path': '',
             'interactiveTime': [],
             'has_use_quick_brush': False,
             'strokes': [],
             'has_use_quick_eraser': False,
             'expansion': 0,
             'feather': 0,
             'reverse': False,
             'custom_matting_id': '',
             'enable_matting_stroke': False,
             'is_clould': '',
             'mask_video_path': '',
             'cloud_product_fps': 0.0},
 'source': 0,
 'source_platform': 0,
 'formula_id': '',
 'check_flag': 62978047,
 'video_algorithm': {'algorithms': [],
                     'time_range': None,
                     'path': '',
                     'gameplay_configs': [],
                     'ai_in_painting_config': [],
                     'complement_frame_config': None,
                     'motion_blur_config': None,
                     'deflicker': None,
                     'noise_reduction': None,
                     'quality_enhance': None,
                     'super_resolution': None,
                     'ai_background_configs': [],
                     'smart_complement_frame': None,
                     'aigc_generate': None,
                     'aigc_generate_list': [],
                     'mouth_shape_driver': None,
                     'ai_expression_driven': None,
                     'ai_motion_driven': None,
                     'image_interpretation': None,
                     'story_video_modify_video_config': {'task_id': '',
                                                         'is_overwrite_last_video': False,
                                                         'tracker_task_id': '',
                                                         'generate_id': '',
                                                         'generate_card_id': ''},
                     'skip_algorithm_index': []},
 'is_unified_beauty_mode': False,
 'is_set_beauty_mode': False,
 'object_locked': None,
 'smart_motion': None,
 'multi_camera_info': None,
 'freeze': None,
 'picture_from': 'none',
 'picture_set_category_id': '',
 'picture_set_category_name': '',
 'team_id': '',
 'local_material_id': '',
 'origin_material_id': '',
 'request_id': '',
 'has_sound_separated': False,
 'is_text_edit_overdub': False,
 'is_ai_generate_content': False,
 'aigc_type': 'none',
 'is_copyright': False,
 'aigc_history_id': '',
 'aigc_item_id': '',
 'local_material_from': '',
 'smart_match_info': None,
 'beauty_face_preset_infos': [],
 'beauty_body_preset_id': '',
 'beauty_face_auto_preset': {'preset_id': '', 'name': '', 'rate_map': '', 'scene': ''},
 'beauty_face_auto_preset_infos': [],
 'beauty_body_auto_preset': None,
 'live_photo_timestamp': -1,
 'live_photo_cover_path': '',
 'content_feature_info': None,
 'corner_pin': None,
 'surface_trackings': [],
 'video_mask_stroke': {'resource_id': '',
                       'path': '',
                       'type': '',
                       'color': '',
                       'size': 0.0,
                       'alpha': 0.0,
                       'distance': 0.0,
                       'texture': 0.0,
                       'horizontal_shift': 0.0,
                       'vertical_shift': 0.0},
 'video_mask_shadow': {'resource_id': '',
                       'path': '',
                       'color': '',
                       'alpha': 0.0,
                       'blur': 0.0,
                       'distance': 0.0,
                       'angle': 0.0},
 'pre_applied_vip_materials': [],
 'workflow_node_id': ''}

AUDIO_MATERIAL = {'id': '',
 'unique_id': '',
 'type': 'extract_music',
 'name': 'guion.wav',
 'duration': 625600000,
 'path': '',
 'category_name': 'local',
 'wave_points': [],
 'music_id': '',
 'app_id': 0,
 'text_id': '',
 'tone_type': '',
 'source_platform': 0,
 'video_id': '',
 'effect_id': '',
 'resource_id': '',
 'third_resource_id': '',
 'category_id': '',
 'intensifies_path': '',
 'formula_id': '',
 'check_flag': 1,
 'team_id': '',
 'local_material_id': '',
 'tone_speaker': '',
 'mock_tone_speaker': '',
 'tone_effect_id': '',
 'tone_effect_name': '',
 'tone_platform': '',
 'cloned_model_type': '',
 'tone_category_id': '',
 'tone_category_name': '',
 'tone_second_category_id': '',
 'tone_second_category_name': '',
 'tone_emotion_name_key': '',
 'tone_emotion_style': '',
 'tone_emotion_role': '',
 'tone_emotion_selection': '',
 'tone_emotion_scale': 0.0,
 'moyin_emotion': '',
 'request_id': '',
 'query': '',
 'search_id': '',
 'sound_separate_type': '',
 'is_text_edit_overdub': False,
 'is_ugc': False,
 'is_ai_clone_tone': False,
 'is_ai_clone_tone_post': False,
 'source_from': '',
 'copyright_limit_type': 'none',
 'aigc_history_id': '',
 'aigc_item_id': '',
 'music_source': '',
 'pgc_id': '',
 'pgc_name': '',
 'similiar_music_info': {'original_song_id': '', 'original_song_name': ''},
 'ai_music_type': 0,
 'ai_music_enter_from': '',
 'lyric_type': 0,
 'tts_task_id': '',
 'tts_generate_scene': '',
 'ai_music_generate_scene': 0,
 'tts_benefit_info': {'benefit_type': 'none',
                      'benefit_log_id': '',
                      'benefit_log_extra': '',
                      'benefit_amount': -1},
 'tts_language_info': None}

PHOTO_SEGMENT = {'id': '',
 'source_timerange': {'start': 0, 'duration': 3133333},
 'target_timerange': {'start': 0, 'duration': 3133333},
 'render_timerange': {'start': 0, 'duration': 0},
 'desc': '',
 'state': 0,
 'speed': 1.0,
 'is_loop': False,
 'is_tone_modify': False,
 'reverse': False,
 'intensifies_audio': False,
 'cartoon': False,
 'volume': 1.0,
 'last_nonzero_volume': 1.0,
 'clip': {'scale': {'x': 1.1489592760180993, 'y': 1.1489592760180993},
          'rotation': 0.0,
          'transform': {'x': 0.0, 'y': 0.0},
          'flip': {'vertical': False, 'horizontal': False},
          'alpha': 1.0},
 'uniform_scale': {'on': True, 'value': 1.0},
 'material_id': '',
 'extra_material_refs': [],
 'render_index': 0,
 'keyframe_refs': [],
 'enable_lut': True,
 'enable_adjust': True,
 'enable_hsl': False,
 'visible': True,
 'group_id': '',
 'enable_color_curves': True,
 'enable_hsl_curves': True,
 'track_render_index': 0,
 'hdr_settings': {'mode': 1, 'intensity': 1.0, 'nits': 1000},
 'hdr_vivid_settings': None,
 'enable_color_wheels': True,
 'track_attribute': 0,
 'is_placeholder': False,
 'template_id': '',
 'enable_smart_color_adjust': False,
 'template_scene': 'default',
 'common_keyframes': [],
 'caption_info': None,
 'responsive_layout': {'enable': False,
                       'target_follow': '',
                       'size_layout': 0,
                       'horizontal_pos_layout': 0,
                       'vertical_pos_layout': 0},
 'enable_color_match_adjust': False,
 'enable_color_correct_adjust': False,
 'enable_adjust_mask': False,
 'raw_segment_id': '',
 'lyric_keyframes': None,
 'enable_video_mask': True,
 'digital_human_template_group_id': '',
 'color_correct_alg_result': '',
 'source': 'segmentsourcenormal',
 'enable_mask_stroke': False,
 'enable_mask_shadow': False,
 'enable_color_adjust_pro': False,
 'segment_color_tag': ''}

AUDIO_SEGMENT = {'id': '',
 'source_timerange': {'start': 0, 'duration': 150000000},
 'target_timerange': {'start': 0, 'duration': 150000000},
 'render_timerange': {'start': 0, 'duration': 0},
 'desc': '',
 'state': 0,
 'speed': 1.0,
 'is_loop': False,
 'is_tone_modify': False,
 'reverse': False,
 'intensifies_audio': False,
 'cartoon': False,
 'volume': 1.0,
 'last_nonzero_volume': 1.0,
 'clip': None,
 'uniform_scale': None,
 'material_id': '',
 'extra_material_refs': [],
 'render_index': 0,
 'keyframe_refs': [],
 'enable_lut': False,
 'enable_adjust': False,
 'enable_hsl': False,
 'visible': True,
 'group_id': '',
 'enable_color_curves': True,
 'enable_hsl_curves': True,
 'track_render_index': 2,
 'hdr_settings': None,
 'hdr_vivid_settings': None,
 'enable_color_wheels': True,
 'track_attribute': 0,
 'is_placeholder': False,
 'template_id': '',
 'enable_smart_color_adjust': False,
 'template_scene': 'default',
 'common_keyframes': [],
 'caption_info': None,
 'responsive_layout': {'enable': False,
                       'target_follow': '',
                       'size_layout': 0,
                       'horizontal_pos_layout': 0,
                       'vertical_pos_layout': 0},
 'enable_color_match_adjust': False,
 'enable_color_correct_adjust': False,
 'enable_adjust_mask': False,
 'raw_segment_id': '',
 'lyric_keyframes': None,
 'enable_video_mask': True,
 'digital_human_template_group_id': '',
 'color_correct_alg_result': '',
 'source': 'segmentsourcenormal',
 'enable_mask_stroke': False,
 'enable_mask_shadow': False,
 'enable_color_adjust_pro': False,
 'segment_color_tag': ''}

VIDEO_TRACK = {'id': '',
 'type': 'video',
 'segments': [{'id': '',
               'source_timerange': {'start': 0, 'duration': 3133333},
               'target_timerange': {'start': 0, 'duration': 3133333},
               'render_timerange': {'start': 0, 'duration': 0},
               'desc': '',
               'state': 0,
               'speed': 1.0,
               'is_loop': False,
               'is_tone_modify': False,
               'reverse': False,
               'intensifies_audio': False,
               'cartoon': False,
               'volume': 1.0,
               'last_nonzero_volume': 1.0,
               'clip': {'scale': {'x': 1.1489592760180993, 'y': 1.1489592760180993},
                        'rotation': 0.0,
                        'transform': {'x': 0.0, 'y': 0.0},
                        'flip': {'vertical': False, 'horizontal': False},
                        'alpha': 1.0},
               'uniform_scale': {'on': True, 'value': 1.0},
               'material_id': '',
               'extra_material_refs': [],
               'render_index': 0,
               'keyframe_refs': [],
               'enable_lut': True,
               'enable_adjust': True,
               'enable_hsl': False,
               'visible': True,
               'group_id': '',
               'enable_color_curves': True,
               'enable_hsl_curves': True,
               'track_render_index': 0,
               'hdr_settings': {'mode': 1, 'intensity': 1.0, 'nits': 1000},
               'hdr_vivid_settings': None,
               'enable_color_wheels': True,
               'track_attribute': 0,
               'is_placeholder': False,
               'template_id': '',
               'enable_smart_color_adjust': False,
               'template_scene': 'default',
               'common_keyframes': [],
               'caption_info': None,
               'responsive_layout': {'enable': False,
                                     'target_follow': '',
                                     'size_layout': 0,
                                     'horizontal_pos_layout': 0,
                                     'vertical_pos_layout': 0},
               'enable_color_match_adjust': False,
               'enable_color_correct_adjust': False,
               'enable_adjust_mask': False,
               'raw_segment_id': '',
               'lyric_keyframes': None,
               'enable_video_mask': True,
               'digital_human_template_group_id': '',
               'color_correct_alg_result': '',
               'source': 'segmentsourcenormal',
               'enable_mask_stroke': False,
               'enable_mask_shadow': False,
               'enable_color_adjust_pro': False,
               'segment_color_tag': ''}],
 'flag': 0,
 'attribute': 0,
 'name': '',
 'is_default_name': True}

AUDIO_TRACK = {'id': '',
 'type': 'audio',
 'segments': [{'id': '',
               'source_timerange': {'start': 0, 'duration': 150000000},
               'target_timerange': {'start': 0, 'duration': 150000000},
               'render_timerange': {'start': 0, 'duration': 0},
               'desc': '',
               'state': 0,
               'speed': 1.0,
               'is_loop': False,
               'is_tone_modify': False,
               'reverse': False,
               'intensifies_audio': False,
               'cartoon': False,
               'volume': 1.0,
               'last_nonzero_volume': 1.0,
               'clip': None,
               'uniform_scale': None,
               'material_id': '',
               'extra_material_refs': [],
               'render_index': 0,
               'keyframe_refs': [],
               'enable_lut': False,
               'enable_adjust': False,
               'enable_hsl': False,
               'visible': True,
               'group_id': '',
               'enable_color_curves': True,
               'enable_hsl_curves': True,
               'track_render_index': 2,
               'hdr_settings': None,
               'hdr_vivid_settings': None,
               'enable_color_wheels': True,
               'track_attribute': 0,
               'is_placeholder': False,
               'template_id': '',
               'enable_smart_color_adjust': False,
               'template_scene': 'default',
               'common_keyframes': [],
               'caption_info': None,
               'responsive_layout': {'enable': False,
                                     'target_follow': '',
                                     'size_layout': 0,
                                     'horizontal_pos_layout': 0,
                                     'vertical_pos_layout': 0},
               'enable_color_match_adjust': False,
               'enable_color_correct_adjust': False,
               'enable_adjust_mask': False,
               'raw_segment_id': '',
               'lyric_keyframes': None,
               'enable_video_mask': True,
               'digital_human_template_group_id': '',
               'color_correct_alg_result': '',
               'source': 'segmentsourcenormal',
               'enable_mask_stroke': False,
               'enable_mask_shadow': False,
               'enable_color_adjust_pro': False,
               'segment_color_tag': ''}],
 'flag': 0,
 'attribute': 0,
 'name': '',
 'is_default_name': True}
