"""Estructuras canonicas de draft CapCut (extraidas de un draft real del usuario).

Al ser la plantilla un esqueleto vacio, se usan estos shapes como modelo
y se adaptan en generate(): ids, rutas, timeranges y duraciones se generan.
*NO* tocar estos valores a mano salvo para adaptarse a una version nueva de CapCut.
"""

from __future__ import annotations

PHOTO_MATERIAL = {'id': '',
 'unique_id': '',
 'type': 'photo',
 'duration': 10800000000,
 'path': '',
 'media_path': '',
 'local_id': '',
 'has_audio': False,
 'reverse_path': '',
 'intensifies_path': '',
 'reverse_intensifies_path': '',
 'intensifies_audio_path': '',
 'cartoon_path': '',
 'width': 1920,
 'height': 1080,
 'category_id': '',
 'category_name': 'local',
 'material_id': '',
 'material_name': '001_Spider-Man balanceándose entre edificios, Spider-Man Hom.jpg',
 'material_url': '',
 'crop': {'upper_left_x': 0.0,
          'upper_left_y': 0.0,
          'upper_right_x': 1.0,
          'upper_right_y': 0.0,
          'lower_left_x': 0.0,
          'lower_left_y': 1.0,
          'lower_right_x': 1.0,
          'lower_right_y': 1.0},
 'crop_ratio': 'free',
 'audio_fade': None,
 'crop_scale': 1.0,
 'extra_type_option': 0,
 'stable': {'stable_level': 0, 'matrix_path': '', 'time_range': {'start': 0, 'duration': 0}},
 'matting': {'flag': 0,
             'path': '',
             'interactiveTime': [],
             'has_use_quick_brush': False,
             'strokes': [],
             'has_use_quick_eraser': False,
             'expansion': 0,
             'feather': 0,
             'reverse': False,
             'custom_matting_id': '',
             'enable_matting_stroke': False,
             'is_clould': '',
             'mask_video_path': '',
             'cloud_product_fps': 0.0},
 'source': 0,
 'source_platform': 0,
 'formula_id': '',
 'check_flag': 62978047,
 'video_algorithm': {'algorithms': [],
                     'time_range': None,
                     'path': '',
                     'gameplay_configs': [],
                     'ai_in_painting_config': [],
                     'complement_frame_config': None,
                     'motion_blur_config': None,
                     'deflicker': None,
                     'noise_reduction': None,
                     'quality_enhance': None,
                     'super_resolution': None,
                     'ai_background_configs': [],
                     'smart_complement_frame': None,
                     'aigc_generate': None,
                     'aigc_generate_list': [],
                     'mouth_shape_driver': None,
                     'ai_expression_driven': None,
                     'ai_motion_driven': None,
                     'image_interpretation': None,
                     'story_video_modify_video_config': {'task_id': '',
                                                         'is_overwrite_last_video': False,
                                                         'tracker_task_id': '',
                                                         'generate_id': '',
                                                         'generate_card_id': ''},
                     'skip_algorithm_index': []},
 'is_unified_beauty_mode': False,
 'is_set_beauty_mode': False,
 'object_locked': None,
 'smart_motion': None,
 'multi_camera_info': None,
 'freeze': None,
 'picture_from': 'none',
 'picture_set_category_id': '',
 'picture_set_category_name': '',
 'team_id': '',
 'local_material_id': '',
 'origin_material_id': '',
 'request_id': '',
 'has_sound_separated': False,
 'is_text_edit_overdub': False,
 'is_ai_generate_content': False,
 'aigc_type': 'none',
 'is_copyright': False,
 'aigc_history_id': '',
 'aigc_item_id': '',
 'local_material_from': '',
 'smart_match_info': None,
 'beauty_face_preset_infos': [],
 'beauty_body_preset_id': '',
 'beauty_face_auto_preset': {'preset_id': '', 'name': '', 'rate_map': '', 'scene': ''},
 'beauty_face_auto_preset_infos': [],
 'beauty_body_auto_preset': None,
 'live_photo_timestamp': -1,
 'live_photo_cover_path': '',
 'content_feature_info': None,
 'corner_pin': None,
 'surface_trackings': [],
 'video_mask_stroke': {'resource_id': '',
                       'path': '',
                       'type': '',
                       'color': '',
                       'size': 0.0,
                       'alpha': 0.0,
                       'distance': 0.0,
                       'texture': 0.0,
                       'horizontal_shift': 0.0,
                       'vertical_shift': 0.0},
 'video_mask_shadow': {'resource_id': '',
                       'path': '',
                       'color': '',
                       'alpha': 0.0,
                       'blur': 0.0,
                       'distance': 0.0,
                       'angle': 0.0},
 'pre_applied_vip_materials': [],
 'workflow_node_id': ''}

AUDIO_MATERIAL = {'id': '',
 'unique_id': '',
 'type': 'extract_music',
 'name': 'guion.wav',
 'duration': 625600000,
 'path': '',
 'category_name': 'local',
 'wave_points': [],
 'music_id': '',
 'app_id': 0,
 'text_id': '',
 'tone_type': '',
 'source_platform': 0,
 'video_id': '',
 'effect_id': '',
 'resource_id': '',
 'third_resource_id': '',
 'category_id': '',
 'intensifies_path': '',
 'formula_id': '',
 'check_flag': 1,
 'team_id': '',
 'local_material_id': '',
 'tone_speaker': '',
 'mock_tone_speaker': '',
 'tone_effect_id': '',
 'tone_effect_name': '',
 'tone_platform': '',
 'cloned_model_type': '',
 'tone_category_id': '',
 'tone_category_name': '',
 'tone_second_category_id': '',
 'tone_second_category_name': '',
 'tone_emotion_name_key': '',
 'tone_emotion_style': '',
 'tone_emotion_role': '',
 'tone_emotion_selection': '',
 'tone_emotion_scale': 0.0,
 'moyin_emotion': '',
 'request_id': '',
 'query': '',
 'search_id': '',
 'sound_separate_type': '',
 'is_text_edit_overdub': False,
 'is_ugc': False,
 'is_ai_clone_tone': False,
 'is_ai_clone_tone_post': False,
 'source_from': '',
 'copyright_limit_type': 'none',
 'aigc_history_id': '',
 'aigc_item_id': '',
 'music_source': '',
 'pgc_id': '',
 'pgc_name': '',
 'similiar_music_info': {'original_song_id': '', 'original_song_name': ''},
 'ai_music_type': 0,
 'ai_music_enter_from': '',
 'lyric_type': 0,
 'tts_task_id': '',
 'tts_generate_scene': '',
 'ai_music_generate_scene': 0,
 'tts_benefit_info': {'benefit_type': 'none',
                      'benefit_log_id': '',
                      'benefit_log_extra': '',
                      'benefit_amount': -1},
 'tts_language_info': None}

PHOTO_SEGMENT = {'id': '',
 'source_timerange': {'start': 0, 'duration': 3133333},
 'target_timerange': {'start': 0, 'duration': 3133333},
 'render_timerange': {'start': 0, 'duration': 0},
 'desc': '',
 'state': 0,
 'speed': 1.0,
 'is_loop': False,
 'is_tone_modify': False,
 'reverse': False,
 'intensifies_audio': False,
 'cartoon': False,
 'volume': 1.0,
 'last_nonzero_volume': 1.0,
 'clip': {'scale': {'x': 1.1489592760180993, 'y': 1.1489592760180993},
          'rotation': 0.0,
          'transform': {'x': 0.0, 'y': 0.0},
          'flip': {'vertical': False, 'horizontal': False},
          'alpha': 1.0},
 'uniform_scale': {'on': True, 'value': 1.0},
 'material_id': '',
 'extra_material_refs': [],
 'render_index': 0,
 'keyframe_refs': [],
 'enable_lut': True,
 'enable_adjust': True,
 'enable_hsl': False,
 'visible': True,
 'group_id': '',
 'enable_color_curves': True,
 'enable_hsl_curves': True,
 'track_render_index': 0,
 'hdr_settings': {'mode': 1, 'intensity': 1.0, 'nits': 1000},
 'hdr_vivid_settings': None,
 'enable_color_wheels': True,
 'track_attribute': 0,
 'is_placeholder': False,
 'template_id': '',
 'enable_smart_color_adjust': False,
 'template_scene': 'default',
 'common_keyframes': [],
 'caption_info': None,
 'responsive_layout': {'enable': False,
                       'target_follow': '',
                       'size_layout': 0,
                       'horizontal_pos_layout': 0,
                       'vertical_pos_layout': 0},
 'enable_color_match_adjust': False,
 'enable_color_correct_adjust': False,
 'enable_adjust_mask': False,
 'raw_segment_id': '',
 'lyric_keyframes': None,
 'enable_video_mask': True,
 'digital_human_template_group_id': '',
 'color_correct_alg_result': '',
 'source': 'segmentsourcenormal',
 'enable_mask_stroke': False,
 'enable_mask_shadow': False,
 'enable_color_adjust_pro': False,
 'segment_color_tag': ''}

AUDIO_SEGMENT = {'id': '',
 'source_timerange': {'start': 0, 'duration': 150000000},
 'target_timerange': {'start': 0, 'duration': 150000000},
 'render_timerange': {'start': 0, 'duration': 0},
 'desc': '',
 'state': 0,
 'speed': 1.0,
 'is_loop': False,
 'is_tone_modify': False,
 'reverse': False,
 'intensifies_audio': False,
 'cartoon': False,
 'volume': 1.0,
 'last_nonzero_volume': 1.0,
 'clip': None,
 'uniform_scale': None,
 'material_id': '',
 'extra_material_refs': [],
 'render_index': 0,
 'keyframe_refs': [],
 'enable_lut': False,
 'enable_adjust': False,
 'enable_hsl': False,
 'visible': True,
 'group_id': '',
 'enable_color_curves': True,
 'enable_hsl_curves': True,
 'track_render_index': 2,
 'hdr_settings': None,
 'hdr_vivid_settings': None,
 'enable_color_wheels': True,
 'track_attribute': 0,
 'is_placeholder': False,
 'template_id': '',
 'enable_smart_color_adjust': False,
 'template_scene': 'default',
 'common_keyframes': [],
 'caption_info': None,
 'responsive_layout': {'enable': False,
                       'target_follow': '',
                       'size_layout': 0,
                       'horizontal_pos_layout': 0,
                       'vertical_pos_layout': 0},
 'enable_color_match_adjust': False,
 'enable_color_correct_adjust': False,
 'enable_adjust_mask': False,
 'raw_segment_id': '',
 'lyric_keyframes': None,
 'enable_video_mask': True,
 'digital_human_template_group_id': '',
 'color_correct_alg_result': '',
 'source': 'segmentsourcenormal',
 'enable_mask_stroke': False,
 'enable_mask_shadow': False,
 'enable_color_adjust_pro': False,
 'segment_color_tag': ''}

VIDEO_TRACK = {'id': '',
 'type': 'video',
 'segments': [{'id': '',
               'source_timerange': {'start': 0, 'duration': 3133333},
               'target_timerange': {'start': 0, 'duration': 3133333},
               'render_timerange': {'start': 0, 'duration': 0},
               'desc': '',
               'state': 0,
               'speed': 1.0,
               'is_loop': False,
               'is_tone_modify': False,
               'reverse': False,
               'intensifies_audio': False,
               'cartoon': False,
               'volume': 1.0,
               'last_nonzero_volume': 1.0,
               'clip': {'scale': {'x': 1.1489592760180993, 'y': 1.1489592760180993},
                        'rotation': 0.0,
                        'transform': {'x': 0.0, 'y': 0.0},
                        'flip': {'vertical': False, 'horizontal': False},
                        'alpha': 1.0},
               'uniform_scale': {'on': True, 'value': 1.0},
               'material_id': '',
               'extra_material_refs': [],
               'render_index': 0,
               'keyframe_refs': [],
               'enable_lut': True,
               'enable_adjust': True,
               'enable_hsl': False,
               'visible': True,
               'group_id': '',
               'enable_color_curves': True,
               'enable_hsl_curves': True,
               'track_render_index': 0,
               'hdr_settings': {'mode': 1, 'intensity': 1.0, 'nits': 1000},
               'hdr_vivid_settings': None,
               'enable_color_wheels': True,
               'track_attribute': 0,
               'is_placeholder': False,
               'template_id': '',
               'enable_smart_color_adjust': False,
               'template_scene': 'default',
               'common_keyframes': [],
               'caption_info': None,
               'responsive_layout': {'enable': False,
                                     'target_follow': '',
                                     'size_layout': 0,
                                     'horizontal_pos_layout': 0,
                                     'vertical_pos_layout': 0},
               'enable_color_match_adjust': False,
               'enable_color_correct_adjust': False,
               'enable_adjust_mask': False,
               'raw_segment_id': '',
               'lyric_keyframes': None,
               'enable_video_mask': True,
               'digital_human_template_group_id': '',
               'color_correct_alg_result': '',
               'source': 'segmentsourcenormal',
               'enable_mask_stroke': False,
               'enable_mask_shadow': False,
               'enable_color_adjust_pro': False,
               'segment_color_tag': ''}],
 'flag': 0,
 'attribute': 0,
 'name': '',
 'is_default_name': True}

TEXT_MATERIAL = {
    'id': '', 'name': '', 'type': 'text',
    'recognize_task_id': '', 'recognize_text': '', 'recognize_model': '',
    'punc_model': '', 'base_content': '',
    # content ES un JSON string con el texto y sus estilos (mismo formato que
    # el draft real 0921). Se construye en src/core/subtitles.py.
    'content': '',
    'words': {'start_time': [], 'end_time': [], 'text': []},
    'current_words': {'start_time': [], 'end_time': [], 'text': []},
    'global_alpha': 1.0,
    'combo_info': {'text_templates': []},
    'caption_template_info': {'resource_id': '', 'third_resource_id': '',
                              'resource_name': '', 'category_id': '',
                              'category_name': '', 'effect_id': '',
                              'request_id': '', 'path': '', 'is_new': False,
                              'source_platform': 0},
    'layer_weight': 1, 'letter_spacing': 0.0, 'text_curve': None,
    'text_loop_on_path': False, 'offset_on_path': 0.0,
    'enable_path_typesetting': False, 'text_exceeds_path_process_type': 0,
    'text_typesetting_paths': None, 'text_typesetting_paths_file': '',
    'text_typesetting_path_index': 0, 'line_spacing': 0.02,
    # -- trazo (stroke) ---------------------------------------------------
    'border_alpha': 1.0, 'border_color': '', 'border_width': 0.08,
    'border_mode': 0,
    # -- sombra (shadow) --------------------------------------------------
    'has_shadow': False, 'shadow_color': '#000000', 'shadow_alpha': 0.9,
    'shadow_smoothing': 0.45, 'shadow_distance': 5.0,
    'shadow_point': {'x': 0.6363961030678928, 'y': -0.6363961030678928},
    'shadow_angle': -45.0, 'shadow_thickness_projection_enable': False,
    'shadow_thickness_projection_angle': 0.0,
    'shadow_thickness_projection_distance': 0.0,
    'style_name': '',
    # -- tipo de letra ----------------------------------------------------
    'text_color': '#FFFFFF', 'text_alpha': 1.0,
    'font_name': '', 'font_title': 'none', 'font_size': 15.0,
    'font_path': '', 'font_id': '', 'font_resource_id': '',
    'initial_scale': 1.0, 'font_url': '',
    'typesetting': 0, 'alignment': 1, 'line_feed': 1,
    'use_effect_default_color': True, 'is_rich_text': False,
    'shape_clip_x': False, 'shape_clip_y': False, 'ktv_color': '',
    'text_to_audio_ids': [], 'bold_width': 0.0, 'italic_degree': 0,
    'underline': False, 'underline_width': 0.05, 'underline_offset': 0.22,
    'sub_type': 0, 'check_flag': 7, 'text_size': 30,
    'font_category_name': '', 'font_source_platform': 0,
    'font_third_resource_id': '', 'font_category_id': '',
    'add_type': 0, 'operation_type': 0, 'recognize_type': 0, 'fonts': [],
    'background_color': '', 'background_alpha': 1.0, 'background_style': 0,
    'background_round_radius': 0.0, 'background_width': 0.14,
    'background_height': 0.14, 'background_vertical_offset': 0.0,
    'background_horizontal_offset': 0.0, 'background_fill': '',
    'single_char_bg_enable': False, 'single_char_bg_color': '',
    'single_char_bg_alpha': 1.0, 'single_char_bg_round_radius': 0.3,
    'single_char_bg_width': 0.0, 'single_char_bg_height': 0.0,
    'single_char_bg_vertical_offset': 0.0,
    'single_char_bg_horizontal_offset': 0.0,
    'font_team_id': '', 'tts_auto_update': False,
    'text_preset_resource_id': '', 'group_id': '', 'preset_id': '',
    'preset_name': '', 'preset_category': '', 'preset_category_id': '',
    'preset_index': 0, 'preset_has_set_alignment': False,
    'force_apply_line_max_width': False, 'language': '',
    'relevance_segment': [], 'original_size': [], 'fixed_width': -1.0,
    'fixed_height': -1.0, 'autoAdaptCanvasEnabled': False,
    'line_max_width': 0.82, 'oneline_cutoff': False, 'cutoff_postfix': '',
    'subtitle_template_original_fontsize': 0.0, 'subtitle_keywords': None,
    'inner_padding': -1.0, 'multi_language_current': 'none',
    'source_from': '', 'is_lyric_effect': False, 'lyric_group_id': '',
    'lyrics_template': {'resource_id': '', 'resource_name': '', 'panel': '',
                        'effect_id': '', 'path': '', 'category_id': '',
                        'category_name': '', 'request_id': ''},
    'is_batch_replace': False, 'is_words_linear': False, 'ssml_content': '',
    'subtitle_keywords_config': None, 'sub_template_id': -1,
    'translate_original_text': '',
}

TEXT_SEGMENT = {
    'id': '', 'source_timerange': None,
    'target_timerange': {'start': 0, 'duration': 200000},
    'render_timerange': {'start': 0, 'duration': 0},
    'desc': '', 'state': 0, 'speed': 1.0, 'is_loop': False,
    'is_tone_modify': False, 'reverse': False, 'intensifies_audio': False,
    'cartoon': False, 'volume': 1.0, 'last_nonzero_volume': 1.0,
    'clip': {'scale': {'x': 1.0, 'y': 1.0}, 'rotation': 0.0,
             'transform': {'x': 0.0, 'y': 0.0},
             'flip': {'vertical': False, 'horizontal': False},
             'alpha': 1.0},
    'uniform_scale': {'on': True, 'value': 1.0}, 'material_id': '',
    'extra_material_refs': [], 'render_index': 14000,
    'keyframe_refs': [], 'enable_lut': False, 'enable_adjust': False,
    'enable_hsl': False, 'visible': True, 'group_id': '',
    'enable_color_curves': True, 'enable_hsl_curves': True,
    'track_render_index': 1, 'hdr_settings': None,
    'hdr_vivid_settings': None, 'enable_color_wheels': True,
    'track_attribute': 0, 'is_placeholder': False, 'template_id': '',
    'enable_smart_color_adjust': False, 'template_scene': 'default',
    'common_keyframes': [], 'caption_info': None,
    'responsive_layout': {'enable': False, 'target_follow': '',
                          'size_layout': 0, 'horizontal_pos_layout': 0,
                          'vertical_pos_layout': 0},
    'enable_color_match_adjust': False, 'enable_color_correct_adjust': False,
    'enable_adjust_mask': False, 'raw_segment_id': '',
    'lyric_keyframes': None, 'enable_video_mask': True,
    'digital_human_template_group_id': '', 'color_correct_alg_result': '',
    'source': 'segmentsourcenormal', 'enable_mask_stroke': False,
    'enable_mask_shadow': False, 'enable_color_adjust_pro': False,
    'segment_color_tag': '',
}

TEXT_TRACK = {'id': '', 'type': 'text', 'segments': [], 'flag': 0,
              'attribute': 0, 'name': '', 'is_default_name': True}


AUDIO_TRACK = {'id': '',
 'type': 'audio',
 'segments': [{'id': '',
               'source_timerange': {'start': 0, 'duration': 150000000},
               'target_timerange': {'start': 0, 'duration': 150000000},
               'render_timerange': {'start': 0, 'duration': 0},
               'desc': '',
               'state': 0,
               'speed': 1.0,
               'is_loop': False,
               'is_tone_modify': False,
               'reverse': False,
               'intensifies_audio': False,
               'cartoon': False,
               'volume': 1.0,
               'last_nonzero_volume': 1.0,
               'clip': None,
               'uniform_scale': None,
               'material_id': '',
               'extra_material_refs': [],
               'render_index': 0,
               'keyframe_refs': [],
               'enable_lut': False,
               'enable_adjust': False,
               'enable_hsl': False,
               'visible': True,
               'group_id': '',
               'enable_color_curves': True,
               'enable_hsl_curves': True,
               'track_render_index': 2,
               'hdr_settings': None,
               'hdr_vivid_settings': None,
               'enable_color_wheels': True,
               'track_attribute': 0,
               'is_placeholder': False,
               'template_id': '',
               'enable_smart_color_adjust': False,
               'template_scene': 'default',
               'common_keyframes': [],
               'caption_info': None,
               'responsive_layout': {'enable': False,
                                     'target_follow': '',
                                     'size_layout': 0,
                                     'horizontal_pos_layout': 0,
                                     'vertical_pos_layout': 0},
               'enable_color_match_adjust': False,
               'enable_color_correct_adjust': False,
               'enable_adjust_mask': False,
               'raw_segment_id': '',
               'lyric_keyframes': None,
               'enable_video_mask': True,
               'digital_human_template_group_id': '',
               'color_correct_alg_result': '',
               'source': 'segmentsourcenormal',
               'enable_mask_stroke': False,
               'enable_mask_shadow': False,
               'enable_color_adjust_pro': False,
               'segment_color_tag': ''}],
 'flag': 0,
 'attribute': 0,
 'name': '',
 'is_default_name': True}
